require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'coverage/**/*'
    - 'examples/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - '**/*.gemspec'
    - 'lib/generators/**/*'

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/generators/**/*'
    - 'lib/**/concerns.rb'
  ExcludedMethods:
    - 'class_methods'

Metrics/ClassLength:
  Exclude:
    - 'lib/generators/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'lib/generators/**/*'
  AllowedMethods:
    - 'track_form_duration'

Metrics/AbcSize:
  Max: 55

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

# Gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

# Naming
Naming/PredicateMethod:
  Exclude:
    - 'spec/**/*'

# RSpec
Capybara/RSpec/PredicateMatcher:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  Enabled: false
